global:
  name: consul
  image: hashicorp/consul-enterprise:1.8-ent
  datacenter: cluster-2
  tls:
    enabled: true
    verify: false
    caCert:
      secretName: consul-federation
      secretKey: caCert
    caKey:
      secretName: consul-federation
      secretKey: caKey
  federation:
    enabled: true
server:
  replicas: 1
  bootstrapExpect: 1
  affinity: ""
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  extraVolumes:
  - type: secret
    name: consul-federation
    items:
      - key: serverConfigJSON
        path: config.json
    load: true
connectInject:
  enabled: true
ui:
  service:
    type: NodePort
meshGateway:
  enabled: true
  replicas: 1
  wanAddress:
    source: Service
  service:
    type: NodePort
    nodePort: 30000
  affinity: ""
ingressGateways:
  enabled: true
  defaults:
    replicas: 1
    service:
      type: NodePort
      ports:
        - port: 30443
          nodePort: 30443
        - port: 30080
          nodePort: 30080
        - port: 30088
          nodePort: 30088
    affinity: ""
  gateways:
    - name: dashboard-ingress-gateway
terminatingGateways:
  enabled: false