global:
  name: consul
  image: hashicorp/consul-enterprise:1.8-ent
  datacenter: cluster-1
  federation:
    enabled: true
    createFederationSecret: true
  tls:
    enabled: true
    verify: false
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  affinity: ""
connectInject:
  enabled: true
ui:
  service:
    type: NodePort
meshGateway:
  enabled: true
  replicas: 1
  wanAddress:
    source: Service
  service:
    type: NodePort
    nodePort: 30000
  affinity: ""
ingressGateways:
  enabled: true
  defaults:
    replicas: 1
    service:
      type: NodePort
      ports:
        - port: 30443
          nodePort: 30443
        - port: 30080
          nodePort: 30080
        - port: 30088
          nodePort: 30088
    affinity: ""
  gateways:
    - name: dashboard-ingress-gateway
terminatingGateways:
  enabled: true
  defaults:
    replicas: 1
    affinity: ""
  gateways:
    - name: counting-terminating-gateway
